version: "3.3"

networks:
  wms:

volumes:
  data:

services:

  external-service:
    build:
      context: ./external-service
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - wms

  warehousing-management:
    build:
      context: ./warehousing-management
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - wms

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - wms

  nacos:
    image: nacos/nacos-server:1.3.0
    ports:
      - "8848:8848"
    environment:
      - "MODE=standalone"
    networks:
      - wms

  mysql_external:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=external"
    volumes:
      - data:/var/lib/mysql
    networks:
      - wms

  mysql_warehousing:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=warehousing"
    volumes:
      - data:/var/lib/mysql
    networks:
      - wms