server:
  port: 8102
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.57.133.233:3306/warehouse?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 543312abc
  #nacos配置
  application:
    name: warehousing-management
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
#        server-addr: 39.107.156.214:8848
        server-addr: localhost:8848
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl